---
- name: maven configuration
  hosts: mavenserver
  become: yes

  roles:
    - common
    - maven

- name: tomcat configuration
  hosts: tomcatserver
  become: yes

  roles: 
    - common
    - tomcat
